# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'doanmanhsonha'
  imageName: 'pipelines-dotnet-core-docker'

steps:
#- script: |
#    docker build -t $(dockerId)/$(imageName) .
#    docker login -u $(dockerId) -p $env:pswd
#    docker push $(dockerId)/$(imageName)
#  env:
#    pswd: $(dockerPassword)

- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(mySecret)"

    # Using the env var directly:
    Write-Host "This does not work: $env:MYSECRET"

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: $(mySecret)